### ISSUE TITLE
Apns

### ISSUE THREAD

**Issue by OrdenKrieger** [DirtyUnicorns/android_vendor_du#2]
Is it normal that i face problems with the apn when i build the rom for a unofficial device? I get no mobile connection and my APN list is empty. But if i pull the apns-conf and selective-spn-conf from cm, mobile data is working fine.

With du apn:
http://pastebin.com/xQ7XMdix

With cm apn: 
http://pastebin.com/8t4paGpm

**Comment by nychitman1** [comment]
We don't do Github issues. Report on JIRA.
